### PR TITLE
Hide reply link on comments

### PR DESCRIPTION
**Pull request by kpengboy**
Fugly kludge because rt#7210 was the last straw for me

Ideally this would be a plugin or something, but I'm not
knowledgeable enough to make one for the present

### CODE REVIEW

**Comment by nattofriends** [comment]
Just going to point out this doesn't help with email

**Comment by dkess** [comment]
Not sure how most of these incidents happen, but email already has a decent deterrent built-in-- the reply-to header is different for replies than in comments, so as long as you don't change the To: address while you compose the email there isn't much risk.

**Comment by kpengboy** [comment]
I'll (try to) do a more precise enumeration of why these mistakes happen
when I get some free time. Of course, help is also always appreciated.

**Comment by kpengboy** [comment]
Modified the patch to make it detect comments the proper way (instead of matching on the description text).

**Pull request merged**
