### PR TITLE
Add failure notifications for Jenkins

### PR DESCRIPTION
**Pull request by jvperrin**
This makes Jenkins send a failure notification to both Slack and email when builds fail. I'm guessing we want this on all branches, not just master, I think that would be best.

The email and Slack message look like this:

email-failure
jenkins-failure

### CODE REVIEW

**Comment by matthew-mcallister** [comment]
> slack
> not irc

May as well post it to Twitter and Google hangouts while you're at it.

**Comment by jvperrin** [comment]
lol!

Well, Slack will bridge to IRC soon anyway, so there's that :P

**Comment by jvperrin** [comment]
Yes, not sure if we want that or not, but it does.

**Comment by jvperrin** [comment]
(the email shows it failing on a non-master build with rt/jenkins-failure-emails instead of rt/master)

**Pull request merged**
